development:
  adapter: postgresql
  encoding: utf8
  database: wasistdas_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: travis_ci_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: wasistdas_production
  pool: 5
  username:
  password:
